### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ceydaduzgec** [dberkerdem/SWE573_Term_Project#27]
Sorry to barge in, I was curious about your repo.
While looking through it I saw a typo and wanted to let you know.
https://github.com/dberkerdem/SWE573_Term_Project/blob/main/core/models.py#L13

**Comment by dberkerdem** [comment]
Typo is fixed in [f32a0ea](https://github.com/dberkerdem/SWE573_Term_Project/commit/f32a0ea9a5a6ce143e6b3a1ddc98920703679a7a).
